/*
 * Copyright (C) 2026 Devout9527
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This file is part of TexInject.
 * TexInject is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 *
 * TexInject is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along
 * with TexInject. If not, see <https://www.gnu.org/licenses/>.
 */
// 自动生成：内嵌的 .py/.mcp 全局加载器源码（来自 全局加载mcp和py.py，原样）。
package com.kael.texinject.mcp;

public final class McpLoaderSource {
    public static final String CODE =
        "# -*- coding: utf-8 -*-\n"
        + "\"\"\"Global .py/.mcp loader for z1yr.\n"
        + "\n"
        + "Follows the same persistent eventUtil pattern as auto_tool.py: a tick\n"
        + "listener stays alive across world changes and keeps the chat listener\n"
        + "registered on the current eventUtil instance. The py/mcp loader logic is\n"
        + "self-contained, and z1yr's own loader is never patched.\n"
        + "\"\"\"\n"
        + "\n"
        + "import hashlib\n"
        + "import os\n"
        + "import re\n"
        + "import sys\n"
        + "\n"
        + "import mod.client.extraClientApi as clientApi\n"
        + "\n"
        + "try:\n"
        + "    unicode\n"
        + "except NameError:\n"
        + "    unicode = str\n"
        + "\n"
        + "_LOADER_MARK = \"_z1yr_global_loader_running\"\n"
        + "_CHAT_MARK = \"_z1yr_global_loader_chat_registered\"\n"
        + "\n"
        + "_LISTENER = None\n"
        + "_LOADED_SCRIPTS = {}\n"
        + "_SCRIPT_COUNTER = [0]\n"
        + "\n"
        + "\n"
        + "def _marker_holder():\n"
        + "    try:\n"
        + "        import _pynetmodule\n"
        + "        return _pynetmodule\n"
        + "    except Exception:\n"
        + "        return sys\n"
        + "\n"
        + "\n"
        + "def _get_sys():\n"
        + "    try:\n"
        + "        return clientApi.GetSystem(\"z1yr\", \"Z1yrClientSystem\")\n"
        + "    except Exception:\n"
        + "        return None\n"
        + "\n"
        + "\n"
        + "def _notify(msg):\n"
        + "    try:\n"
        + "        _safe_notify_message(msg)\n"
        + "        return\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    try:\n"
        + "        import gui\n"
        + "        gui.set_left_corner_notify_msg(msg)\n"
        + "        return\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    try:\n"
        + "        sys_ref = _get_sys()\n"
        + "        if sys_ref is not None and hasattr(sys_ref, \"_notify\"):\n"
        + "            sys_ref._notify(msg, force=True)\n"
        + "            return\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    print(msg)\n"
        + "\n"
        + "\n"
        + "def _strip_quotes(path):\n"
        + "    path = path.strip()\n"
        + "    while len(path) >= 2 and path[0] in ('\"', \"'\") and path[-1] == path[0]:\n"
        + "        path = path[1:-1].strip()\n"
        + "    if path and path[0] in ('\"', \"'\"):\n"
        + "        path = path[1:]\n"
        + "    if path and path[-1] in ('\"', \"'\"):\n"
        + "        path = path[:-1]\n"
        + "    return path.strip()\n"
        + "\n"
        + "\n"
        + "def _looks_like_bare_name(path):\n"
        + "    if not path:\n"
        + "        return False\n"
        + "    if path.startswith(('\\\\', '/')):\n"
        + "        return False\n"
        + "    if len(path) >= 2 and path[1] == ':':\n"
        + "        return False\n"
        + "    if path.lower().startswith('file:'):\n"
        + "        return False\n"
        + "    if '/' in path or '\\\\' in path:\n"
        + "        return False\n"
        + "    return True\n"
        + "\n"
        + "\n"
        + "def _engine_bases():\n"
        + "    bases = []\n"
        + "    try:\n"
        + "        for attr in ('GetLogDir', 'GetGameDir'):\n"
        + "            fn = getattr(clientApi, attr, None)\n"
        + "            if fn:\n"
        + "                base = fn()\n"
        + "                if base:\n"
        + "                    bases.append(str(base))\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    return bases\n"
        + "\n"
        + "\n"
        + "def _z1yr_root_candidates():\n"
        + "    roots = []\n"
        + "    seen = set()\n"
        + "\n"
        + "    def add(root):\n"
        + "        root = str(root)\n"
        + "        low = root.replace('\\\\', '/').lower()\n"
        + "        if 'minecraftworlds' in low or '/db/' in low or low.endswith('/db'):\n"
        + "            return\n"
        + "        if root not in seen:\n"
        + "            seen.add(root)\n"
        + "            roots.append(root)\n"
        + "\n"
        + "    if os.name == 'nt':\n"
        + "        add('C:\\\\z1yr')\n"
        + "    else:\n"
        + "        add('/storage/emulated/0/Android/data/com.netease.x19/files/z1yr')\n"
        + "        try:\n"
        + "            home = os.path.expanduser('~')\n"
        + "            if home and home != '~':\n"
        + "                add(os.path.join(home, 'Documents', 'z1yr'))\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "    for base in _engine_bases():\n"
        + "        add(os.path.join(base, 'z1yr'))\n"
        + "    try:\n"
        + "        add(os.path.dirname(os.path.abspath(__file__)))\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    return roots\n"
        + "\n"
        + "\n"
        + "def _find_in_z1yr(filename, subfolder=None):\n"
        + "    seen = set()\n"
        + "    for root in _z1yr_root_candidates():\n"
        + "        root = str(root)\n"
        + "        if root in seen:\n"
        + "            continue\n"
        + "        seen.add(root)\n"
        + "        if subfolder:\n"
        + "            path = os.path.join(root, subfolder, filename)\n"
        + "            if os.path.isfile(path):\n"
        + "                return path\n"
        + "        path = os.path.join(root, filename)\n"
        + "        if os.path.isfile(path):\n"
        + "            return path\n"
        + "    return None\n"
        + "\n"
        + "\n"
        + "def _resolve_z1yr_quick(name, ext):\n"
        + "    names = [name]\n"
        + "    if not name.lower().endswith(ext):\n"
        + "        names.append(name + ext)\n"
        + "    subfolder = 'mcp' if ext.lower() == '.mcp' else 'py'\n"
        + "    for candidate in names:\n"
        + "        found = _find_in_z1yr(candidate, subfolder)\n"
        + "        if found:\n"
        + "            return found\n"
        + "        found = _find_in_z1yr(candidate)\n"
        + "        if found:\n"
        + "            return found\n"
        + "    return os.path.join(_z1yr_root_candidates()[0], subfolder, names[-1])\n"
        + "\n"
        + "\n"
        + "def normalize_script_path(raw, ext):\n"
        + "    path = raw.strip()\n"
        + "    try:\n"
        + "        if isinstance(path, str) and not isinstance(path, unicode):\n"
        + "            try:\n"
        + "                path = path.decode('utf-8')\n"
        + "            except UnicodeDecodeError:\n"
        + "                path = path.decode('gbk', 'replace')\n"
        + "    except NameError:\n"
        + "        pass\n"
        + "    path = path.replace(u'\\u201c', '\"').replace(u'\\u201d', '\"')\n"
        + "    path = path.replace(u'\\u2018', \"'\").replace(u'\\u2019', \"'\")\n"
        + "    path = _strip_quotes(path)\n"
        + "    low = path.lower()\n"
        + "    if low.startswith('file:///'):\n"
        + "        path = path[len('file://'):]\n"
        + "        if os.name == 'nt' and path.startswith('/'):\n"
        + "            path = path[1:]\n"
        + "    elif low.startswith('file://'):\n"
        + "        path = path[len('file://'):]\n"
        + "        if path.startswith('/'):\n"
        + "            path = path[1:]\n"
        + "    elif low.startswith('file:'):\n"
        + "        path = path[len('file:'):]\n"
        + "        if path.startswith('/'):\n"
        + "            path = path[1:]\n"
        + "    if _looks_like_bare_name(path):\n"
        + "        return _resolve_z1yr_quick(path, ext)\n"
        + "    if len(path) >= 3 and path[1] == ':' and path[2] not in ('\\\\', '/'):\n"
        + "        path = path[:2] + '\\\\' + path[2:]\n"
        + "    path = os.path.expanduser(path)\n"
        + "    path = os.path.normpath(path)\n"
        + "    path = os.path.abspath(path)\n"
        + "    if not path.lower().endswith(ext):\n"
        + "        if not os.path.isfile(path) and os.path.isfile(path + ext):\n"
        + "            path += ext\n"
        + "        elif not os.path.isfile(path):\n"
        + "            path += ext\n"
        + "    return path\n"
        + "\n"
        + "\n"
        + "def _unique_module_name(path):\n"
        + "    try:\n"
        + "        norm_path = os.path.normcase(os.path.abspath(path))\n"
        + "        digest = hashlib.md5(norm_path.encode('utf-8', 'replace')).hexdigest()[:12]\n"
        + "    except Exception:\n"
        + "        digest = str(abs(hash(path)))\n"
        + "    _SCRIPT_COUNTER[0] += 1\n"
        + "    return 'z1yr_py_{}_{}'.format(digest, _SCRIPT_COUNTER[0])\n"
        + "\n"
        + "\n"
        + "def _add_script_dir(path):\n"
        + "    script_dir = os.path.dirname(os.path.abspath(path))\n"
        + "    if script_dir and script_dir not in sys.path:\n"
        + "        sys.path.insert(0, script_dir)\n"
        + "\n"
        + "\n"
        + "def _load_script_module(path, mod_name):\n"
        + "    try:\n"
        + "        import imp\n"
        + "    except ImportError:\n"
        + "        imp = None\n"
        + "    if imp is not None:\n"
        + "        return imp.load_source(mod_name, path)\n"
        + "    import importlib.machinery\n"
        + "    loader = importlib.machinery.SourceFileLoader(mod_name, path)\n"
        + "    return loader.load_module()\n"
        + "\n"
        + "\n"
        + "def _execute_py_file(path):\n"
        + "    try:\n"
        + "        with open(path, 'r') as f:\n"
        + "            source = f.read()\n"
        + "    except Exception as e:\n"
        + "        return u'\\u00a7c\\u65e0\\u6cd5\\u8bfb\\u53d6\\u811a\\u672c: %s' % e\n"
        + "    try:\n"
        + "        code = compile(source, path, 'exec')\n"
        + "        try:\n"
        + "            import fop\n"
        + "        except ImportError:\n"
        + "            fop = None\n"
        + "        if fop is not None:\n"
        + "            try:\n"
        + "                fop.new_module('', code, [os.path.dirname(os.path.abspath(path))])\n"
        + "                return None\n"
        + "            except Exception as fop_error:\n"
        + "                print('[global-loader] fop load failed, fallback: ' + str(fop_error))\n"
        + "        mod_name = _unique_module_name(path)\n"
        + "        _add_script_dir(path)\n"
        + "        mod = _load_script_module(path, mod_name)\n"
        + "        _LOADED_SCRIPTS[mod_name] = mod\n"
        + "        return None\n"
        + "    except Exception as e:\n"
        + "        try:\n"
        + "            import traceback\n"
        + "            traceback.print_exc()\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "        return u'\\u00a7c\\u811a\\u672c\\u6267\\u884c\\u5931\\u8d25: %s' % e\n"
        + "\n"
        + "\n"
        + "def load_py(raw_path):\n"
        + "    path = normalize_script_path(raw_path, '.py')\n"
        + "    if not os.path.isfile(path):\n"
        + "        print('[global-loader] python script not found: ' + path)\n"
        + "        return u'\\u00a7c\\u672a\\u627e\\u5230 Python \\u811a\\u672c: ' + path\n"
        + "    error = _execute_py_file(path)\n"
        + "    if error:\n"
        + "        print('[global-loader] python script failed: ' + path)\n"
        + "        return error\n"
        + "    print('[global-loader] python script loaded: ' + path)\n"
        + "    return u'\\u00a7aPython \\u811a\\u672c\\u52a0\\u8f7d\\u6210\\u529f: ' + path\n"
        + "\n"
        + "\n"
        + "def _get_mcp_notify():\n"
        + "    try:\n"
        + "        import _notify as engine_notify\n"
        + "        if hasattr(engine_notify, 'add_mod_mcp'):\n"
        + "            return engine_notify\n"
        + "    except ImportError:\n"
        + "        pass\n"
        + "    try:\n"
        + "        engine_notify = __import__('minecraft.notify', fromlist=['notify'])\n"
        + "        if hasattr(engine_notify, 'add_mod_mcp'):\n"
        + "            return engine_notify\n"
        + "    except ImportError:\n"
        + "        pass\n"
        + "    try:\n"
        + "        import notify as engine_notify\n"
        + "        if hasattr(engine_notify, 'add_mod_mcp'):\n"
        + "            return engine_notify\n"
        + "    except ImportError:\n"
        + "        pass\n"
        + "    return None\n"
        + "\n"
        + "\n"
        + "def _to_engine_path(path):\n"
        + "    if getattr(sys, 'version_info', (2,))[0] >= 3:\n"
        + "        return path\n"
        + "    try:\n"
        + "        if isinstance(path, unicode):\n"
        + "            if os.name == 'nt':\n"
        + "                return path.encode('gbk', 'replace')\n"
        + "            return path.encode('utf-8', 'replace')\n"
        + "    except NameError:\n"
        + "        pass\n"
        + "    return path\n"
        + "\n"
        + "\n"
        + "def _remove_from_sys_path(path):\n"
        + "    if not path:\n"
        + "        return\n"
        + "    norm = os.path.normcase(os.path.normpath(path))\n"
        + "    for p in list(sys.path):\n"
        + "        try:\n"
        + "            if os.path.normcase(os.path.normpath(p)) == norm:\n"
        + "                sys.path.remove(p)\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "\n"
        + "\n"
        + "def _clear_importer_cache(path):\n"
        + "    if not path:\n"
        + "        return\n"
        + "    cache = getattr(sys, 'path_importer_cache', None)\n"
        + "    if cache is None:\n"
        + "        return\n"
        + "    norm = os.path.normcase(os.path.normpath(path))\n"
        + "    for key in list(cache):\n"
        + "        try:\n"
        + "            if os.path.normcase(os.path.normpath(key)) == norm:\n"
        + "                del cache[key]\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "\n"
        + "\n"
        + "def _safe_notify_message(message):\n"
        + "    def _notify(msg):\n"
        + "        if isinstance(msg, unicode):\n"
        + "            try:\n"
        + "                msg = msg.encode('utf-8', 'replace')\n"
        + "            except Exception:\n"
        + "                try:\n"
        + "                    msg = msg.encode('gbk', 'replace')\n"
        + "                except Exception:\n"
        + "                    pass\n"
        + "        comp = clientApi.GetEngineCompFactory().CreateTextNotifyClient(\n"
        + "            clientApi.GetLevelId())\n"
        + "        comp.SetLeftCornerNotify(msg)\n"
        + "\n"
        + "    try:\n"
        + "        _notify(message)\n"
        + "        return\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    if isinstance(message, bytes):\n"
        + "        try:\n"
        + "            _notify(message.decode('utf-8'))\n"
        + "            return\n"
        + "        except UnicodeDecodeError:\n"
        + "            try:\n"
        + "                _notify(message.decode('gbk', 'replace'))\n"
        + "                return\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "        except Exception:\n"
        + "            try:\n"
        + "                _notify(message.decode('gbk', 'replace'))\n"
        + "                return\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "    else:\n"
        + "        try:\n"
        + "            _notify(message.encode('gbk', 'replace'))\n"
        + "            return\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "    try:\n"
        + "        import gui\n"
        + "        gui_message = message\n"
        + "        if isinstance(gui_message, unicode):\n"
        + "            try:\n"
        + "                gui_message = gui_message.encode('utf-8', 'replace')\n"
        + "            except Exception:\n"
        + "                try:\n"
        + "                    gui_message = gui_message.encode('gbk', 'replace')\n"
        + "                except Exception:\n"
        + "                    pass\n"
        + "        gui.set_left_corner_notify_msg(gui_message)\n"
        + "        return\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "\n"
        + "\n"
        + "def _patch_z1yr_notify(mod_name):\n"
        + "    for suffix in ('api.notify', 'api.utils'):\n"
        + "        try:\n"
        + "            __import__(mod_name + '.' + suffix, fromlist=[''])\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "        module = sys.modules.get(mod_name + '.' + suffix)\n"
        + "        if module is None:\n"
        + "            continue\n"
        + "        try:\n"
        + "            module.clientMessageF = _safe_notify_message\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "\n"
        + "\n"
        + "def _bridge_func_accepts_arg(func):\n"
        + "    code = getattr(func, '__code__', None)\n"
        + "    if code is None:\n"
        + "        im_func = getattr(func, 'im_func', None)\n"
        + "        if im_func is not None:\n"
        + "            code = getattr(im_func, 'func_code', None)\n"
        + "    if code is None:\n"
        + "        return True\n"
        + "    arg_count = getattr(code, 'co_argcount', 1)\n"
        + "    if (getattr(func, '__self__', None) is not None or\n"
        + "            getattr(func, 'im_self', None) is not None):\n"
        + "        arg_count = max(0, arg_count - 1)\n"
        + "    return arg_count > 0\n"
        + "\n"
        + "\n"
        + "def _safe_call_func(func, args):\n"
        + "    if not _bridge_func_accepts_arg(func):\n"
        + "        return func()\n"
        + "    if args is None:\n"
        + "        args = {}\n"
        + "    return func(args)\n"
        + "\n"
        + "\n"
        + "def _make_bridge_listener(event_name):\n"
        + "    def _on_event(self, args=None):\n"
        + "        _SYSTEM_BRIDGE.dispatch(event_name, args)\n"
        + "    listener_cls = type('BridgeListener', (object,), {'_on_event': _on_event})\n"
        + "    return listener_cls()\n"
        + "\n"
        + "\n"
        + "class _SystemEventBridge(object):\n"
        + "    def __init__(self):\n"
        + "        self._records = []\n"
        + "        self._capture_class = None\n"
        + "        self._capture_original = None\n"
        + "        self._capture_active = False\n"
        + "        self._patched_classes = []\n"
        + "        self._registered = {}\n"
        + "\n"
        + "    def clear(self):\n"
        + "        self._records = []\n"
        + "        self._patched_classes = []\n"
        + "        self._registered = {}\n"
        + "\n"
        + "    def set_registered_system(self, system, namespace, system_name):\n"
        + "        try:\n"
        + "            self._registered[id(system)] = (namespace, system_name)\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "\n"
        + "    def begin_capture(self):\n"
        + "        self.clear()\n"
        + "        try:\n"
        + "            client_system_cls = clientApi.GetClientSystemCls()\n"
        + "            original = getattr(client_system_cls, 'ListenForEvent', None)\n"
        + "            if original is not None:\n"
        + "                client_system_cls.ListenForEvent = self._make_capture_func()\n"
        + "                self._capture_class = client_system_cls\n"
        + "                self._capture_original = original\n"
        + "                self._capture_active = True\n"
        + "        except Exception as e:\n"
        + "            print('[global-loader] event capture unavailable: ' + str(e))\n"
        + "        return True\n"
        + "\n"
        + "    def _make_capture_func(self):\n"
        + "        def _capture_listen(system, namespace, system_name, event_name,\n"
        + "                            instance, func):\n"
        + "            try:\n"
        + "                self._records.append(\n"
        + "                    (system, event_name, func, namespace, system_name,\n"
        + "                     instance))\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "        return _capture_listen\n"
        + "\n"
        + "    def patch_class(self, cls_path):\n"
        + "        try:\n"
        + "            module_path, _, class_name = cls_path.rpartition('.')\n"
        + "            if not module_path or not class_name:\n"
        + "                return\n"
        + "            module = __import__(module_path, fromlist=[''])\n"
        + "            cls = getattr(module, class_name, None)\n"
        + "            if cls is None:\n"
        + "                return\n"
        + "            if any(patched_cls is cls for patched_cls, _old in\n"
        + "                   self._patched_classes):\n"
        + "                return\n"
        + "            original = getattr(cls, 'ListenForEvent', None)\n"
        + "            if original is None:\n"
        + "                return\n"
        + "            cls.ListenForEvent = self._make_capture_func()\n"
        + "            self._patched_classes.append((cls, original))\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "\n"
        + "    def end_capture(self):\n"
        + "        if self._capture_active and self._capture_class is not None:\n"
        + "            try:\n"
        + "                self._capture_class.ListenForEvent = self._capture_original\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "        for cls, original in self._patched_classes:\n"
        + "            try:\n"
        + "                cls.ListenForEvent = original\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "        self._capture_active = False\n"
        + "        self._capture_class = None\n"
        + "        self._capture_original = None\n"
        + "        self._patched_classes = []\n"
        + "\n"
        + "    def dispatch(self, event_name, args=None):\n"
        + "        for system, ev, func, _ns, _sn, _inst in list(self._records):\n"
        + "            if ev != event_name:\n"
        + "                continue\n"
        + "            try:\n"
        + "                _safe_call_func(func, args)\n"
        + "            except Exception as e:\n"
        + "                print('[global-loader] bridge event %s error: %s' %\n"
        + "                      (event_name, str(e)))\n"
        + "\n"
        + "    def attach(self, event_util=None):\n"
        + "        if not self._records:\n"
        + "            return\n"
        + "        if event_util is None:\n"
        + "            try:\n"
        + "                import mod.common.eventUtil as event_util_module\n"
        + "                event_util = event_util_module.instance\n"
        + "            except Exception:\n"
        + "                return\n"
        + "        event_util_id = id(event_util)\n"
        + "        marked = _BRIDGE_MARKERS.get(event_util_id)\n"
        + "        if marked is None:\n"
        + "            marked = set()\n"
        + "            _BRIDGE_MARKERS[event_util_id] = marked\n"
        + "        skip_events = ('UiInitFinished', 'LoadClientAddonScriptsAfter',\n"
        + "                       'OnScriptTickClient', 'ClickChatSendClientEvent')\n"
        + "        for system, event_name, func, namespace, system_name, instance in \\\n"
        + "                self._records:\n"
        + "            if event_name in skip_events or event_name in marked:\n"
        + "                continue\n"
        + "            try:\n"
        + "                listener = _make_bridge_listener(event_name)\n"
        + "                event_util.ListenForEngineClient(\n"
        + "                    event_name, listener, listener._on_event, 10)\n"
        + "                marked.add(event_name)\n"
        + "            except Exception as e:\n"
        + "                print('[global-loader] bridge listen error %s: %s' %\n"
        + "                      (event_name, str(e)))\n"
        + "                try:\n"
        + "                    system.ListenForEvent(\n"
        + "                        namespace, system_name, event_name, instance, func)\n"
        + "                except Exception as fallback_error:\n"
        + "                    print('[global-loader] bridge fallback error %s: %s' %\n"
        + "                          (event_name, str(fallback_error)))\n"
        + "\n"
        + "    def cleanup_stale(self):\n"
        + "        if not self._records:\n"
        + "            return\n"
        + "        try:\n"
        + "            local_player = clientApi.GetLocalPlayerId()\n"
        + "        except Exception:\n"
        + "            return\n"
        + "        kept = []\n"
        + "        for system, event_name, func, namespace, system_name, _inst in \\\n"
        + "                self._records:\n"
        + "            if hasattr(system, 'thisPlayer'):\n"
        + "                if getattr(system, 'thisPlayer', None) != local_player:\n"
        + "                    continue\n"
        + "            registered_info = self._registered.get(id(system))\n"
        + "            if registered_info is not None:\n"
        + "                reg_ns, reg_sn = registered_info\n"
        + "                try:\n"
        + "                    current = clientApi.GetSystem(reg_ns, reg_sn)\n"
        + "                except Exception:\n"
        + "                    current = None\n"
        + "                if current is not None and current is not system:\n"
        + "                    continue\n"
        + "                if current is None:\n"
        + "                    system_register = _get_client_system_register()\n"
        + "                    found = False\n"
        + "                    if system_register is not None:\n"
        + "                        for registry in ('systemInstances',\n"
        + "                                         'newSystemInstances'):\n"
        + "                            entries = getattr(system_register, registry, None)\n"
        + "                            if not entries:\n"
        + "                                continue\n"
        + "                            if any(inst is system\n"
        + "                                   for inst in entries.values()):\n"
        + "                                found = True\n"
        + "                                break\n"
        + "                    if system_register is not None and not found:\n"
        + "                        continue\n"
        + "            kept.append(\n"
        + "                (system, event_name, func, namespace, system_name, _inst))\n"
        + "        self._records = kept\n"
        + "\n"
        + "\n"
        + "_SYSTEM_BRIDGE = _SystemEventBridge()\n"
        + "_BRIDGE_MARKERS = {}\n"
        + "\n"
        + "\n"
        + "def _cleanup_old_mcp_module(mod_name):\n"
        + "    prefix = mod_name\n"
        + "    for name in [n for n in list(sys.modules)\n"
        + "                 if n == prefix or n.startswith(prefix + '.')]:\n"
        + "        try:\n"
        + "            del sys.modules[name]\n"
        + "        except KeyError:\n"
        + "            pass\n"
        + "    suffix = mod_name.lower() + '.mcp'\n"
        + "    old_paths = []\n"
        + "    for p in list(sys.path):\n"
        + "        try:\n"
        + "            base = os.path.basename(os.path.normpath(p)).lower()\n"
        + "        except Exception:\n"
        + "            base = ''\n"
        + "        if base == suffix or base == mod_name.lower():\n"
        + "            old_paths.append(p)\n"
        + "    for p in old_paths:\n"
        + "        _remove_from_sys_path(p)\n"
        + "        _clear_importer_cache(p)\n"
        + "        mcp_notify = _get_mcp_notify()\n"
        + "        if mcp_notify:\n"
        + "            try:\n"
        + "                mcp_notify.remove_mod_mcp(_to_engine_path(p))\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "    cache = getattr(sys, 'path_importer_cache', None)\n"
        + "    if cache is not None:\n"
        + "        for key in list(cache):\n"
        + "            try:\n"
        + "                if os.path.basename(os.path.normpath(key)).lower() == suffix:\n"
        + "                    del cache[key]\n"
        + "            except Exception:\n"
        + "                pass\n"
        + "    try:\n"
        + "        sys.module_paths.clear()\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "\n"
        + "\n"
        + "def _rollback_mcp(mcp_notify, path):\n"
        + "    try:\n"
        + "        mcp_notify.remove_mod_mcp(_to_engine_path(path))\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    _remove_from_sys_path(path)\n"
        + "    _clear_importer_cache(path)\n"
        + "\n"
        + "\n"
        + "def _get_client_system_register():\n"
        + "    try:\n"
        + "        from common.system.systemRegister import client\n"
        + "        return client\n"
        + "    except ImportError:\n"
        + "        pass\n"
        + "    try:\n"
        + "        import common.system.systemRegister as system_register\n"
        + "        return getattr(system_register, 'client', None)\n"
        + "    except ImportError:\n"
        + "        pass\n"
        + "    try:\n"
        + "        import common.game as game\n"
        + "        app = game.GetClient()\n"
        + "        if app is not None:\n"
        + "            return app._GetSystemRegister()\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    return None\n"
        + "\n"
        + "\n"
        + "def _unregister_system(namespace, system_name):\n"
        + "    system_register = _get_client_system_register()\n"
        + "    if system_register is None:\n"
        + "        return\n"
        + "    try:\n"
        + "        system_register.UnRegisterSystem(namespace, system_name)\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    key = namespace + ':' + system_name\n"
        + "    try:\n"
        + "        system_register.systemInstances.pop(key, None)\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    new_instance = None\n"
        + "    try:\n"
        + "        new_instance = system_register.newSystemInstances.pop(key, None)\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "    if new_instance is not None:\n"
        + "        try:\n"
        + "            new_instance.DestroyEvents()\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "        try:\n"
        + "            new_instance.Destroy()\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "    try:\n"
        + "        system_register.deleteSystemInstances.discard(key)\n"
        + "    except Exception:\n"
        + "        pass\n"
        + "\n"
        + "\n"
        + "def _unregister_systems_for_module(mod_name):\n"
        + "    system_register = _get_client_system_register()\n"
        + "    if system_register is None:\n"
        + "        return\n"
        + "    targets = []\n"
        + "    registries = [\n"
        + "        getattr(system_register, 'systemInstances', None),\n"
        + "        getattr(system_register, 'newSystemInstances', None),\n"
        + "    ]\n"
        + "    for registry in registries:\n"
        + "        if not registry:\n"
        + "            continue\n"
        + "        for key, instance in list(registry.items()):\n"
        + "            try:\n"
        + "                module_name = getattr(instance.__class__, '__module__', '')\n"
        + "            except Exception:\n"
        + "                module_name = ''\n"
        + "            if module_name == mod_name or module_name.startswith(mod_name + '.'):\n"
        + "                if ':' in key:\n"
        + "                    namespace, system_name = key.split(':', 1)\n"
        + "                    targets.append((namespace, system_name))\n"
        + "    for namespace, system_name in targets:\n"
        + "        _unregister_system(namespace, system_name)\n"
        + "\n"
        + "\n"
        + "def _trigger_post_load_events(systems, instances=()):\n"
        + "    called_funcs = set()\n"
        + "    event_names = ('uiinitfinished', 'loadclientaddonscriptsafter')\n"
        + "    method_keys = ('uiinit', 'loadclientaddonscriptsafter')\n"
        + "    objects = list(instances)\n"
        + "    for namespace, system_name, _cls_path in systems:\n"
        + "        try:\n"
        + "            system = clientApi.GetSystem(namespace, system_name)\n"
        + "        except Exception:\n"
        + "            system = None\n"
        + "        if system is None:\n"
        + "            system_register = _get_client_system_register()\n"
        + "            if system_register is not None:\n"
        + "                key = namespace + ':' + system_name\n"
        + "                system = getattr(system_register, 'systemInstances', {}).get(key)\n"
        + "                if system is None:\n"
        + "                    system = getattr(system_register, 'newSystemInstances', {}).get(key)\n"
        + "        if system is not None:\n"
        + "            objects.append(system)\n"
        + "    for system in objects:\n"
        + "        try:\n"
        + "            listen_events = getattr(system, 'nameToListenEvents', {})\n"
        + "        except Exception:\n"
        + "            listen_events = {}\n"
        + "        for event_name, event_list in list(listen_events.items()):\n"
        + "            if event_name.lower() not in event_names:\n"
        + "                continue\n"
        + "            for event in list(event_list):\n"
        + "                try:\n"
        + "                    func = getattr(event, 'funcName', None)\n"
        + "                    if func:\n"
        + "                        if getattr(func, '__self__', None) is None:\n"
        + "                            instance = getattr(event, 'instance', None)\n"
        + "                            if instance is not None:\n"
        + "                                func = getattr(instance, getattr(func, '__name__', ''), func)\n"
        + "                        if func not in called_funcs:\n"
        + "                            func({})\n"
        + "                            called_funcs.add(func)\n"
        + "                except Exception as e:\n"
        + "                    print('[global-loader] post-load event error: ' + str(e))\n"
        + "        for key in dir(system):\n"
        + "            low_key = key.lower()\n"
        + "            if not any(m in low_key for m in method_keys):\n"
        + "                continue\n"
        + "            func = getattr(system, key)\n"
        + "            if not callable(func):\n"
        + "                continue\n"
        + "            if func in called_funcs:\n"
        + "                continue\n"
        + "            try:\n"
        + "                func({})\n"
        + "                called_funcs.add(func)\n"
        + "            except Exception as e:\n"
        + "                print('[global-loader] post-load event error: ' + str(e))\n"
        + "\n"
        + "\n"
        + "def load_mcp(raw_path):\n"
        + "    path = normalize_script_path(raw_path, '.mcp')\n"
        + "    if not os.path.isfile(path):\n"
        + "        return u'\\u00a7c\\u672a\\u627e\\u5230 MCP \\u6587\\u4ef6: ' + path\n"
        + "    base = os.path.basename(path)\n"
        + "    mod_name = base[:-4] if base.lower().endswith('.mcp') else os.path.splitext(base)[0]\n"
        + "    if not mod_name or not re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', mod_name):\n"
        + "        return u'\\u00a7c\\u65e0\\u6548\\u7684 MCP \\u6a21\\u5757\\u540d: ' + base\n"
        + "    mcp_notify = _get_mcp_notify()\n"
        + "    if mcp_notify is None:\n"
        + "        return u'\\u00a7c\\u65e0\\u6cd5\\u83b7\\u53d6 MCP \\u52a0\\u8f7d\\u63a5\\u53e3'\n"
        + "    _SYSTEM_BRIDGE.clear()\n"
        + "    _unregister_systems_for_module(mod_name)\n"
        + "    _unregister_system('Minecraft', mod_name)\n"
        + "    _cleanup_old_mcp_module(mod_name)\n"
        + "    try:\n"
        + "        mcp_notify.add_mod_mcp(_to_engine_path(path))\n"
        + "    except Exception as e:\n"
        + "        return u'\\u00a7c\\u6ce8\\u518c MCP \\u5931\\u8d25: %s' % e\n"
        + "    _remove_from_sys_path(path)\n"
        + "    sys.path.insert(0, path)\n"
        + "    mod_main_path = mod_name + '.modMain'\n"
        + "    try:\n"
        + "        mod = __import__(mod_main_path, fromlist=[''])\n"
        + "    except Exception as first_error:\n"
        + "        lowered = mod_name.lower()\n"
        + "        if lowered == mod_name:\n"
        + "            _rollback_mcp(mcp_notify, path)\n"
        + "            return u'\\u00a7c\\u5bfc\\u5165 MCP \\u5931\\u8d25: %s' % first_error\n"
        + "        try:\n"
        + "            mod = __import__(lowered + '.modMain', fromlist=[''])\n"
        + "            mod_name = lowered\n"
        + "            mod_main_path = lowered + '.modMain'\n"
        + "        except Exception:\n"
        + "            _rollback_mcp(mcp_notify, path)\n"
        + "            return u'\\u00a7c\\u5bfc\\u5165 MCP \\u5931\\u8d25: %s' % first_error\n"
        + "    _patch_z1yr_notify(mod_name)\n"
        + "    instances = []\n"
        + "    init_count = 0\n"
        + "    errors = []\n"
        + "    systems = []\n"
        + "    bridge_captured = _SYSTEM_BRIDGE.begin_capture()\n"
        + "    original_register = getattr(clientApi, 'RegisterSystem', None)\n"
        + "    try:\n"
        + "        if original_register is not None:\n"
        + "            try:\n"
        + "                def _recording_register(namespace, system_name, cls_path):\n"
        + "                    systems.append((namespace, system_name, cls_path))\n"
        + "                    _SYSTEM_BRIDGE.patch_class(cls_path)\n"
        + "                    return original_register(namespace, system_name, cls_path)\n"
        + "                clientApi.RegisterSystem = _recording_register\n"
        + "            except Exception:\n"
        + "                original_register = None\n"
        + "        try:\n"
        + "            for m_key in dir(mod):\n"
        + "                cls = getattr(mod, m_key)\n"
        + "                if not hasattr(cls, 'MOD_NAME'):\n"
        + "                    continue\n"
        + "                try:\n"
        + "                    instance = cls()\n"
        + "                except Exception as e:\n"
        + "                    errors.append('%s() -> %s' % (m_key, e))\n"
        + "                    continue\n"
        + "                instances.append(instance)\n"
        + "                for c_key in dir(instance):\n"
        + "                    func = getattr(instance, c_key)\n"
        + "                    if not hasattr(func, 'InitClient'):\n"
        + "                        continue\n"
        + "                    try:\n"
        + "                        func()\n"
        + "                        init_count += 1\n"
        + "                    except Exception as e:\n"
        + "                        errors.append('%s.%s -> %s' % (m_key, c_key, e))\n"
        + "        finally:\n"
        + "            if original_register is not None:\n"
        + "                try:\n"
        + "                    clientApi.RegisterSystem = original_register\n"
        + "                except Exception:\n"
        + "                    pass\n"
        + "    finally:\n"
        + "        if bridge_captured:\n"
        + "            _SYSTEM_BRIDGE.end_capture()\n"
        + "    _trigger_post_load_events(systems, instances)\n"
        + "    _patch_z1yr_notify(mod_name)\n"
        + "    _SYSTEM_BRIDGE.attach()\n"
        + "    for namespace, system_name, _cls_path in systems:\n"
        + "        try:\n"
        + "            system = clientApi.GetSystem(namespace, system_name)\n"
        + "        except Exception:\n"
        + "            system = None\n"
        + "        if system is not None:\n"
        + "            _SYSTEM_BRIDGE.set_registered_system(\n"
        + "                system, namespace, system_name)\n"
        + "    result = u'\\u00a7aMCP \\u52a0\\u8f7d\\u6210\\u529f [%s]: %s' % (\n"
        + "        mod_name, path)\n"
        + "    if errors:\n"
        + "        print('[global-loader] mcp load errors: ' + ' | '.join(errors[:2]))\n"
        + "    else:\n"
        + "        print('[global-loader] mcp loaded: ' + mod_name)\n"
        + "    return result\n"
        + "\n"
        + "\n"
        + "def _run_loader(cmd, raw):\n"
        + "    if not raw.strip():\n"
        + "        if cmd == \"mcp\":\n"
        + "            _notify(u'\\u00a7c\\u7528\\u6cd5: .mcp <\\u6587\\u4ef6\\u8def\\u5f84'\n"
        + "                    u'\\u6216\\u6587\\u4ef6\\u540d>')\n"
        + "        else:\n"
        + "            _notify(u'\\u00a7c\\u7528\\u6cd5: .py <\\u6587\\u4ef6\\u8def\\u5f84'\n"
        + "                    u'\\u6216\\u6587\\u4ef6\\u540d>')\n"
        + "        return\n"
        + "    try:\n"
        + "        if cmd == \"py\":\n"
        + "            result = load_py(raw)\n"
        + "        else:\n"
        + "            result = load_mcp(raw)\n"
        + "        if result:\n"
        + "            _notify(result)\n"
        + "        else:\n"
        + "            _notify(\"loaded \" + cmd + \": \" + raw)\n"
        + "    except Exception as e:\n"
        + "        if cmd == \"mcp\":\n"
        + "            _notify(u'\\u00a7cMCP \\u547d\\u4ee4\\u9519\\u8bef: ' + str(e))\n"
        + "        else:\n"
        + "            _notify(u'\\u00a7cPython \\u811a\\u672c\\u547d\\u4ee4\\u9519\\u8bef: '\n"
        + "                    + str(e))\n"
        + "\n"
        + "\n"
        + "def _chat_parts(args):\n"
        + "    try:\n"
        + "        msg = args.get(\"message\", \"\")\n"
        + "    except Exception:\n"
        + "        return None, None\n"
        + "    if isinstance(msg, bytes):\n"
        + "        try:\n"
        + "            msg = msg.decode(\"utf-8\", \"replace\")\n"
        + "        except Exception:\n"
        + "            msg = str(msg)\n"
        + "    if not msg.startswith(\".\"):\n"
        + "        return None, None\n"
        + "    line = msg[1:].strip()\n"
        + "    if not line:\n"
        + "        return None, None\n"
        + "    parts = line.split(None, 1)\n"
        + "    cmd = parts[0].lower()\n"
        + "    raw = parts[1] if len(parts) > 1 else \"\"\n"
        + "    return cmd, raw\n"
        + "\n"
        + "\n"
        + "class _GlobalLoaderListener(object):\n"
        + "    def __init__(self):\n"
        + "        self._tick_count = 0\n"
        + "\n"
        + "    def _on_tick(self, args=None):\n"
        + "        self._tick_count += 1\n"
        + "        _SYSTEM_BRIDGE.dispatch(\"OnScriptTickClient\", None)\n"
        + "        if self._tick_count % 20 == 0:\n"
        + "            _SYSTEM_BRIDGE.cleanup_stale()\n"
        + "            _ensure_chat_listener()\n"
        + "            _SYSTEM_BRIDGE.attach()\n"
        + "\n"
        + "    def _on_chat(self, args=None):\n"
        + "        if not isinstance(args, dict):\n"
        + "            return\n"
        + "        cmd, raw = _chat_parts(args)\n"
        + "        try:\n"
        + "            if cmd in (\"py\", \"mcp\"):\n"
        + "                args[\"cancel\"] = True\n"
        + "        except Exception:\n"
        + "            pass\n"
        + "        if cmd in (\"py\", \"mcp\"):\n"
        + "            _run_loader(cmd, raw)\n"
        + "        else:\n"
        + "            _SYSTEM_BRIDGE.dispatch(\"ClickChatSendClientEvent\", args)\n"
        + "\n"
        + "def _ensure_chat_listener(event_util=None):\n"
        + "    global _LISTENER\n"
        + "    if _LISTENER is None:\n"
        + "        _LISTENER = _GlobalLoaderListener()\n"
        + "    if event_util is None:\n"
        + "        try:\n"
        + "            import mod.common.eventUtil as event_util_module\n"
        + "            event_util = event_util_module.instance\n"
        + "        except Exception:\n"
        + "            return\n"
        + "    if getattr(event_util, _CHAT_MARK, False):\n"
        + "        return\n"
        + "    try:\n"
        + "        event_util.ListenForEngineClient(\n"
        + "            \"ClickChatSendClientEvent\", _LISTENER, _LISTENER._on_chat, 10)\n"
        + "        setattr(event_util, _CHAT_MARK, True)\n"
        + "    except Exception as e:\n"
        + "        print(\"[global-loader] chat register error: \" + str(e))\n"
        + "\n"
        + "\n"
        + "def _start(args=None):\n"
        + "    global _LISTENER\n"
        + "    if _LISTENER is None:\n"
        + "        _LISTENER = _GlobalLoaderListener()\n"
        + "    try:\n"
        + "        import mod.common.eventUtil as event_util_module\n"
        + "        event_util = event_util_module.instance\n"
        + "    except Exception as e:\n"
        + "        print(\"[global-loader] event_util unavailable: \" + str(e))\n"
        + "        return False\n"
        + "\n"
        + "    holder = _marker_holder()\n"
        + "    if not getattr(holder, _LOADER_MARK, False):\n"
        + "        try:\n"
        + "            event_util.ListenForEngineClient(\n"
        + "                \"OnScriptTickClient\", _LISTENER, _LISTENER._on_tick, 10)\n"
        + "            setattr(holder, _LOADER_MARK, True)\n"
        + "        except Exception as e:\n"
        + "            print(\"[global-loader] tick register error: \" + str(e))\n"
        + "\n"
        + "    _ensure_chat_listener(event_util)\n"
        + "    print(\"[global-loader] running: global .py/.mcp loader\")\n"
        + "    return True\n"
        + "\n"
        + "\n"
        + "def _schedule_start():\n"
        + "    try:\n"
        + "        game_comp = clientApi.GetEngineCompFactory().CreateGame(clientApi.GetLevelId())\n"
        + "        game_comp.AddTimer(0.5, _start)\n"
        + "    except Exception:\n"
        + "        _start()\n"
        + "\n"
        + "\n"
        + "_schedule_start()\n"
        + "";

    private McpLoaderSource() {
    }
}
