#!/usr/bin/env python3
"""生成全网易版符号签名表 -> signatures.json"""
import json, struct, sys
from elftools.elf.elffile import ELFFile

def insn_mask(w):
    if (w & 0x9F000000) == 0x90000000: return 0x9F00001F, w & 0x9F00001F
    if (w & 0x7C000000) == 0x14000000: return 0xFC000000, w & 0xFC000000
    if (w & 0xFF000010) == 0x54000000: return 0xFF00001F, w & 0xFF00001F
    if (w & 0x3B000000) == 0x18000000: return 0xFF00001F, w & 0xFF00001F
    if (w & 0x7E000000) == 0x34000000: return 0xFF00001F, w & 0xFF00001F
    if (w & 0x7E000000) == 0x36000000: return 0xFFF8001F, w & 0xFFF8001F
    if (w & 0x1F000000) == 0x10000000: return 0x9F00001F, w & 0x9F00001F
    return 0xFFFFFFFF, w

class SO:
    def __init__(self, p):
        self.f = open(p,'rb')
        self.segs=[(s['p_vaddr'],s['p_filesz'],s['p_offset'])
                   for s in ELFFile(self.f).iter_segments() if s['p_type']=='PT_LOAD']
    def read(self, va, n):
        for a,sz,off in self.segs:
            if a <= va < a+sz:
                self.f.seek(off+(va-a)); return self.f.read(n)
        return None

def sig_at(so, va, nbytes=40):
    d = so.read(va, nbytes)
    if not d or len(d) < 16: return None
    words=[struct.unpack('<I',d[i:i+4])[0] for i in range(0,len(d)-3,4)]
    adrp_rd={w & 0x1F for w in words if (w & 0x9F000000)==0x90000000}
    toks=[]
    for w in words:
        if (w & 0x1F000000)==0x11000000 and ((w>>5)&0x1F) in adrp_rd:
            k,v = 0xFFC00000, w & 0xFFC00000
        else:
            k,v = insn_mask(w)
        for b in range(4):
            sh=8*b
            hi='%X'%((v>>(sh+4))&0xF) if (k>>(sh+4))&0xF else '?'
            lo='%X'%((v>>sh)&0xF) if (k>>sh)&0xF else '?'
            toks.append(hi+lo)
    return ' '.join(toks)

if __name__=='__main__':
    FOF, SO5, SO15 = sys.argv[1], sys.argv[2], sys.argv[3]
    base=json.load(open(FOF))
    so5, so15 = SO(SO5), SO(SO15)
    out={"schemaVersion":1,"revision":1,
         "gameVersion":"3.9.15.297907","target":"libminecraftpe.so",
         "note":"auto-generated by siggen/gen_all.py (网易版)",
         "symbols":[]}
    ok=bad=skip=0
    for e in base:
        fn=e['fn']
        entry=None
        for k in ('ptr_395','ptr_3915'):
            v=e.get(k)
            if v: entry=int(v,16) if isinstance(v,str) else v; break
        if not entry: skip+=1; continue
        sigs=[]
        for delta in (0, 16, 32):          # 多候选：从不同位置起算
            s=sig_at(so5, entry+delta)
            if s: sigs.append({"off":delta,"sig":s})
        if not sigs: skip+=1; continue
        # 跨版本验证（有对照的话）
        va15=e.get('ptr_3915')
        verified=None
        if va15:
            va15=int(va15,16) if isinstance(va15,str) else va15
            best=False
            for c in sigs:
                d=so15.read(va15+c["off"], 40)
                if not d: continue
                toks=c["sig"].split()
                good=True
                for i,t in enumerate(toks):
                    if i>=len(d): break
                    m=v=0
                    if t[0]!='?': m|=0xF0; v|=int(t[0],16)<<4
                    if t[1]!='?': m|=0x0F; v|=int(t[1],16)
                    if (d[i]&m)!=v: good=False; break
                if good: best=True; break
            verified=best
        out["symbols"].append({"name":fn,"entry":hex(entry),"sigs":sigs,"crossVersionOk":verified})
        if verified is True: ok+=1
        elif verified is False: bad+=1
        else: skip+=1
    json.dump(out, open('signatures.json','w'), indent=1, ensure_ascii=False)
    print("导出 signatures.json: %d 个符号" % len(out["symbols"]))
    print("  跨版本验证通过 %d | 失败 %d | 无对照 %d" % (ok,bad,skip))
    import os
    print("  文件大小 %d 字节" % os.path.getsize('signatures.json'))
